version: 2.1

jobs: 
  build-medium: 
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps: 
      - checkout
      - run: uname -a
      - run: gcc -o hello_arm hello.c
      - run: ./hello_arm
      - run: file hello_arm
  build-runner: 
    machine: true
    resource_class: kurumai/arm-runner
    steps: 
      - checkout
      - run: uname -a
      - run: gcc -o hello_arm hello.c
      - run: ./hello_arm
      - run: file hello_arm
workflows: 
  build:
    jobs: 
      - build-medium
      - build-runner

