version: 2.1

jobs: 
  build-medium: 
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps: 
      - checkout
      - run: sudo apt-get install intltool
      - run: uname -a
      - run: ./autogen.sh
      - run: ./configure
      - run: make check
  build-runner: 
    machine: true
    resource_class: kurumai/arm-runner
    steps: 
      - checkout
      - run: uname -a
      - run: ./autogen.sh
      - run: ./configure
      - run: make check
workflows: 
  build:
    jobs: 
      #- build-medium
      - build-runner

